CREATE TABLE ALUNO
(
    NR_RGM        NUMBER(8,0) PRIMARY KEY NOT NULL,
    NM_NOME       VARCHAR2(40)NOT NULL,
    NM_PAI        VARCHAR2(40),
    NM_MAE        VARCHAR2(40),
    DT_NASCIMENTO DATE        NOT NULL,
    ID_SEXO       CHAR(1)
    CONSTRAINT ALUNO_ID_SEXO CHECK(ID_SEXO IN ('F', 'M'))
);

CREATE TABLE CLASSE
(
    CD_CLASSE       NUMBER(8,0) PRIMARY KEY NOT NULL,
    NR_AnoLetivo    NUMBER(4,0) NOT NULL,
    NR_SERIE        NUMBER(2,0) NOT NULL,
    SG_TURMA        VARCHAR2(2) NOT NULL,
    CD_ESCOLA       NUMBER(6,0) NOT NULL,
    CD_GRAU         NUMBER(2,0) NOT NULL,
    CD_PERIODO      NUMBER(2,0) NOT NULL
);

CREATE TABLE MATRICULA 
(
    NR_RGM          NUMBER(8,0) NOT NULL,
    CD_CLASSE       NUMBER(8,0) NOT NULL,
    DT_MATRICULA    DATE,
    CONSTRAINT PK_MATRICULA PRIMARY KEY(NR_RGM, CD_CLASSE),
    CONSTRAINT FK_MATRICULA_REF_ALUNO FOREIGN KEY(NR_RGM)
        REFERENCES ALUNO(NR_RGM),
    CONSTRAINT FK_MATRICULA_REF_CLASSE FOREIGN KEY(CD_CLASSE)
        REFERENCES CLASSE(CD_CLASSE)
);

